package auto;
// Generated 18-feb-2019 16:40:31 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JoinedTransportationvehicle generated by hbm2java
 */
@Entity
@Table(name = "joined_transportationvehicle", catalog = "jpa")
public class JoinedTransportationvehicle implements java.io.Serializable {

	private int idVehicle;
	private int loadCapacity;

	public JoinedTransportationvehicle() {
	}

	public JoinedTransportationvehicle(int idVehicle, int loadCapacity) {
		this.idVehicle = idVehicle;
		this.loadCapacity = loadCapacity;
	}

	@Id

	@Column(name = "idVehicle", unique = true, nullable = false)
	public int getIdVehicle() {
		return this.idVehicle;
	}

	public void setIdVehicle(int idVehicle) {
		this.idVehicle = idVehicle;
	}

	@Column(name = "loadCapacity", nullable = false)
	public int getLoadCapacity() {
		return this.loadCapacity;
	}

	public void setLoadCapacity(int loadCapacity) {
		this.loadCapacity = loadCapacity;
	}

}
