package auto;
// Generated 18-feb-2019 16:40:31 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JoinedPassengervehicle generated by hbm2java
 */
@Entity
@Table(name = "joined_passengervehicle", catalog = "jpa")
public class JoinedPassengervehicle implements java.io.Serializable {

	private int idVehicle;
	private int noOfpassengers;

	public JoinedPassengervehicle() {
	}

	public JoinedPassengervehicle(int idVehicle, int noOfpassengers) {
		this.idVehicle = idVehicle;
		this.noOfpassengers = noOfpassengers;
	}

	@Id

	@Column(name = "idVehicle", unique = true, nullable = false)
	public int getIdVehicle() {
		return this.idVehicle;
	}

	public void setIdVehicle(int idVehicle) {
		this.idVehicle = idVehicle;
	}

	@Column(name = "noOfpassengers", nullable = false)
	public int getNoOfpassengers() {
		return this.noOfpassengers;
	}

	public void setNoOfpassengers(int noOfpassengers) {
		this.noOfpassengers = noOfpassengers;
	}

}
