package auto;
// Generated 18-feb-2019 16:40:31 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PostTag generated by hbm2java
 */
@Entity
@Table(name = "post_tag", catalog = "jpa")
public class PostTag implements java.io.Serializable {

	private PostTagId id;

	public PostTag() {
	}

	public PostTag(PostTagId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "postId", column = @Column(name = "post_id", nullable = false)),
			@AttributeOverride(name = "tagId", column = @Column(name = "tag_id", nullable = false)) })
	public PostTagId getId() {
		return this.id;
	}

	public void setId(PostTagId id) {
		this.id = id;
	}

}
