package auto;
// Generated 18-feb-2019 16:40:31 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PostTagId generated by hbm2java
 */
@Embeddable
public class PostTagId implements java.io.Serializable {

	private long postId;
	private long tagId;

	public PostTagId() {
	}

	public PostTagId(long postId, long tagId) {
		this.postId = postId;
		this.tagId = tagId;
	}

	@Column(name = "post_id", nullable = false)
	public long getPostId() {
		return this.postId;
	}

	public void setPostId(long postId) {
		this.postId = postId;
	}

	@Column(name = "tag_id", nullable = false)
	public long getTagId() {
		return this.tagId;
	}

	public void setTagId(long tagId) {
		this.tagId = tagId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PostTagId))
			return false;
		PostTagId castOther = (PostTagId) other;

		return (this.getPostId() == castOther.getPostId()) && (this.getTagId() == castOther.getTagId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPostId();
		result = 37 * result + (int) this.getTagId();
		return result;
	}

}
