package auto;
// Generated 18-feb-2019 16:40:31 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SingleTableVehicle generated by hbm2java
 */
@Entity
@Table(name = "single_table_vehicle", catalog = "jpa")
public class SingleTableVehicle implements java.io.Serializable {

	private Integer idVehicle;
	private String vehicleType;
	private String manufacturer;
	private Integer noOfpassengers;
	private Integer loadCapacity;

	public SingleTableVehicle() {
	}

	public SingleTableVehicle(String vehicleType) {
		this.vehicleType = vehicleType;
	}

	public SingleTableVehicle(String vehicleType, String manufacturer, Integer noOfpassengers, Integer loadCapacity) {
		this.vehicleType = vehicleType;
		this.manufacturer = manufacturer;
		this.noOfpassengers = noOfpassengers;
		this.loadCapacity = loadCapacity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idVehicle", unique = true, nullable = false)
	public Integer getIdVehicle() {
		return this.idVehicle;
	}

	public void setIdVehicle(Integer idVehicle) {
		this.idVehicle = idVehicle;
	}

	@Column(name = "VEHICLE_TYPE", nullable = false, length = 31)
	public String getVehicleType() {
		return this.vehicleType;
	}

	public void setVehicleType(String vehicleType) {
		this.vehicleType = vehicleType;
	}

	@Column(name = "manufacturer")
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "noOfpassengers")
	public Integer getNoOfpassengers() {
		return this.noOfpassengers;
	}

	public void setNoOfpassengers(Integer noOfpassengers) {
		this.noOfpassengers = noOfpassengers;
	}

	@Column(name = "loadCapacity")
	public Integer getLoadCapacity() {
		return this.loadCapacity;
	}

	public void setLoadCapacity(Integer loadCapacity) {
		this.loadCapacity = loadCapacity;
	}

}
