package auto;
// Generated 18-feb-2019 16:40:31 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TablePerClassPassengervehicle generated by hbm2java
 */
@Entity
@Table(name = "table_per_class_passengervehicle", catalog = "jpa")
public class TablePerClassPassengervehicle implements java.io.Serializable {

	private int idVehicle;
	private String manufacturer;
	private int noOfpassengers;

	public TablePerClassPassengervehicle() {
	}

	public TablePerClassPassengervehicle(int idVehicle, int noOfpassengers) {
		this.idVehicle = idVehicle;
		this.noOfpassengers = noOfpassengers;
	}

	public TablePerClassPassengervehicle(int idVehicle, String manufacturer, int noOfpassengers) {
		this.idVehicle = idVehicle;
		this.manufacturer = manufacturer;
		this.noOfpassengers = noOfpassengers;
	}

	@Id

	@Column(name = "idVehicle", unique = true, nullable = false)
	public int getIdVehicle() {
		return this.idVehicle;
	}

	public void setIdVehicle(int idVehicle) {
		this.idVehicle = idVehicle;
	}

	@Column(name = "manufacturer")
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "noOfpassengers", nullable = false)
	public int getNoOfpassengers() {
		return this.noOfpassengers;
	}

	public void setNoOfpassengers(int noOfpassengers) {
		this.noOfpassengers = noOfpassengers;
	}

}
