package auto;
// Generated 18-feb-2019 16:40:31 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TablePerClassTransportationvehicle generated by hbm2java
 */
@Entity
@Table(name = "table_per_class_transportationvehicle", catalog = "jpa")
public class TablePerClassTransportationvehicle implements java.io.Serializable {

	private int idVehicle;
	private String manufacturer;
	private int loadCapacity;

	public TablePerClassTransportationvehicle() {
	}

	public TablePerClassTransportationvehicle(int idVehicle, int loadCapacity) {
		this.idVehicle = idVehicle;
		this.loadCapacity = loadCapacity;
	}

	public TablePerClassTransportationvehicle(int idVehicle, String manufacturer, int loadCapacity) {
		this.idVehicle = idVehicle;
		this.manufacturer = manufacturer;
		this.loadCapacity = loadCapacity;
	}

	@Id

	@Column(name = "idVehicle", unique = true, nullable = false)
	public int getIdVehicle() {
		return this.idVehicle;
	}

	public void setIdVehicle(int idVehicle) {
		this.idVehicle = idVehicle;
	}

	@Column(name = "manufacturer")
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "loadCapacity", nullable = false)
	public int getLoadCapacity() {
		return this.loadCapacity;
	}

	public void setLoadCapacity(int loadCapacity) {
		this.loadCapacity = loadCapacity;
	}

}
