package elements;

public enum FuncionJPQL {

	ABS, CASE, COALESCE, CONCAT, CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP, LENGTH, LOCATE, LOWER, MOD, NULLIF,
	SQRT, SUBSTRING, TRIM, UPPER, COUNT

}
