package elements;

public enum FuncionSQL92 {

	AVG, COUNT, MAX, MIN, SUM, ABS, ACOS, ADD_MONTHS, ASCII, ASIN, ATAN, ATAN2, CASE, CAST, CEILING, CHAR, CHR,
	COALESCE, CONCAT, CONVERT, COS, CURDATE, CURTIME, DATABASE, DAYNAME, DAYOFMONTH, DAYOFWEEK, DAYOFYEAR, DB_NAME,
	DECODE, DEGREES, EXP, FLOOR, GREATEST, HOUR, IFNULL, INITCAP, INSERT, INSTR, LAST_DAY, LCASE, LEAST, LEFT, LENGTH,
	LOCATE, LOG10, LOWER, LPAD, LTRIM, MINUTE, MOD, MONTH, MONTHNAME, MONTHS_BETWEEN, NEXT_DAY, NOW, NULLIF, NVL, PI,
	POWER, PREFIX, RADIANS, RAND, REPEAT, REPLACE, RIGHT, ROUND, ROWID, RPAD, RTRIM, SECOND, SIGN, SIN, SQRT, SUBSTR,
	SUBSTRING, SUFFIX, SYSDATE, SYSTIME, SYSTIMESTAMP, TAN, TO_CHAR, TO_DAT, TO_NUMBER, TO_TIME, TO_TIMESTAMP,
	TRANSLATE, UCASE, UPPER, USER, WEEK, YEAR

}
